// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByID = `-- name: GetProductByID :one
SELECT
    id,
    sku,
    name,
    description,
    unit,
    min_stock,
    on_hand,
    is_active,
    CASE
        WHEN on_hand = 0 THEN 'OUT OF STOCK'
        WHEN on_hand < min_stock THEN 'LOW'
        ELSE 'HEALTHY'
    END::text AS stock_status,
    version,
    created_at,
    updated_at
FROM products
WHERE id = $1
`

type GetProductByIDRow struct {
	ID          pgtype.UUID
	Sku         string
	Name        string
	Description pgtype.Text
	Unit        string
	MinStock    int32
	OnHand      int32
	IsActive    bool
	StockStatus string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.MinStock,
		&i.OnHand,
		&i.IsActive,
		&i.StockStatus,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    sku,
    name,
    description,
    unit,
    min_stock,
    on_hand,
    is_active,
    CASE
        WHEN on_hand = 0 THEN 'OUT OF STOCK'
        WHEN on_hand < min_stock THEN 'LOW'
        ELSE 'HEALTHY'
    END::text AS stock_status,
    version,
    created_at,
    updated_at
FROM products
WHERE is_active = TRUE
ORDER BY sku ASC, id ASC
`

type ListProductsRow struct {
	ID          pgtype.UUID
	Sku         string
	Name        string
	Description pgtype.Text
	Unit        string
	MinStock    int32
	OnHand      int32
	IsActive    bool
	StockStatus string
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.MinStock,
			&i.OnHand,
			&i.IsActive,
			&i.StockStatus,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
